# SPDX-License-Identifier: MIT

PACKAGE_NAME="rp1-gpclk-dkms"
PACKAGE_VERSION="0.0.0-phase5.23"

BUILT_MODULE_NAME[0]="rp1_gpclk_dkms"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates/dkms"

MAKE[0]="make KERNEL_BUILD=${kernel_source_dir}"
CLEAN="make KERNEL_BUILD=${kernel_source_dir} clean"
AUTOINSTALL="yes"
