// SPDX-License-Identifier: MIT
#include <stddef.h>
#include <stdio.h>

#include "linux/rp1_gpclk.h"

#define ASSERT_EQ(actual, expected) _Static_assert((actual) == (expected), #actual)

ASSERT_EQ(sizeof(struct rp1_gpclk_uapi_header), 8);
ASSERT_EQ(sizeof(struct rp1_gpclk_query), 296);
ASSERT_EQ(sizeof(struct rp1_gpclk_release), 56);
ASSERT_EQ(sizeof(struct rp1_gpclk_snapshot), 384);
ASSERT_EQ(sizeof(struct rp1_gpclk_acquire), 64);
ASSERT_EQ(sizeof(struct rp1_gpclk_tone), 24);
ASSERT_EQ(sizeof(struct rp1_gpclk_event), 16);
ASSERT_EQ(sizeof(struct rp1_gpclk_submit_events), 112);
ASSERT_EQ(sizeof(struct rp1_gpclk_stop), 56);
ASSERT_EQ(sizeof(struct rp1_gpclk_state_request), 88);
ASSERT_EQ(offsetof(struct rp1_gpclk_query, capabilities), 24);
ASSERT_EQ(offsetof(struct rp1_gpclk_submit_events, events_ptr), 32);

ASSERT_EQ(RP1_GPCLK_IOC_MAGIC, 0xb8);
ASSERT_EQ(_IOC_TYPE(RP1_GPCLK_IOC_QUERY), RP1_GPCLK_IOC_MAGIC);
ASSERT_EQ(_IOC_NR(RP1_GPCLK_IOC_QUERY), 0x20);
ASSERT_EQ(_IOC_NR(RP1_GPCLK_IOC_ACQUIRE), 0x21);
ASSERT_EQ(_IOC_NR(RP1_GPCLK_IOC_SUBMIT_EVENTS), 0x23);
ASSERT_EQ(_IOC_NR(RP1_GPCLK_IOC_STOP), 0x24);
ASSERT_EQ(_IOC_NR(RP1_GPCLK_IOC_GET_STATE), 0x25);
ASSERT_EQ(_IOC_NR(RP1_GPCLK_IOC_RELEASE), 0x26);
ASSERT_EQ(_IOC_NR(RP1_GPCLK_IOC_GET_SNAPSHOT), 0x28);
ASSERT_EQ(_IOC_SIZE(RP1_GPCLK_IOC_ACQUIRE),
          sizeof(struct rp1_gpclk_acquire));
ASSERT_EQ(_IOC_SIZE(RP1_GPCLK_IOC_GET_SNAPSHOT),
          sizeof(struct rp1_gpclk_snapshot));
ASSERT_EQ(_IOC_SIZE(RP1_GPCLK_IOC_QUERY), sizeof(struct rp1_gpclk_query));
ASSERT_EQ(_IOC_DIR(RP1_GPCLK_IOC_STOP), _IOC_WRITE);
ASSERT_EQ(_IOC_DIR(RP1_GPCLK_IOC_GET_STATE), _IOC_READ | _IOC_WRITE);

ASSERT_EQ(RP1_GPCLK_ROUTE_GPIO4, 1);
ASSERT_EQ(RP1_GPCLK_ROUTE_GPIO20, 2);
ASSERT_EQ(RP1_GPCLK_COMPAT_QUALIFIED, 1);
ASSERT_EQ(RP1_GPCLK_COMPAT_EXPERIMENTAL, 2);
ASSERT_EQ(RP1_GPCLK_COMPAT_COMPATIBLE_UNQUALIFIED, 3);
ASSERT_EQ(RP1_GPCLK_COMPAT_UNAVAILABLE, 4);
ASSERT_EQ(RP1_GPCLK_COMPAT_REJECTED, 5);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_MANIFEST_MISSING, 1);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_IDENTITY_UNKNOWN, 2);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_IDENTITY_MISMATCH, 3);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_BUILD_UNSUPPORTED, 4);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_SIGNATURE_REJECTED, 5);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_RESOURCE_UNAVAILABLE, 6);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_RESOURCE_CONFLICT, 7);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_SELF_TEST_FAILED, 8);
ASSERT_EQ(RP1_GPCLK_COMPAT_REASON_CLEANUP_LATCHED, 9);
ASSERT_EQ(RP1_GPCLK_STATE_IDLE, 0);
ASSERT_EQ(RP1_GPCLK_STATE_RUNNING, 1);
ASSERT_EQ(RP1_GPCLK_STATE_DRAINING, 2);
ASSERT_EQ(RP1_GPCLK_STATE_COMPLETE, 3);
ASSERT_EQ(RP1_GPCLK_STATE_FAILED, 4);
ASSERT_EQ(RP1_GPCLK_STATE_DEAD, 5);
ASSERT_EQ(RP1_GPCLK_REASON_NONE, 0);
ASSERT_EQ(RP1_GPCLK_REASON_COMPLETE, 1);
ASSERT_EQ(RP1_GPCLK_REASON_STOPPED, 2);
ASSERT_EQ(RP1_GPCLK_REASON_OWNER_CLOSED, 3);
ASSERT_EQ(RP1_GPCLK_REASON_PROVIDER_REMOVED, 4);
ASSERT_EQ(RP1_GPCLK_REASON_DEADLINE_MISSED, 5);
ASSERT_EQ(RP1_GPCLK_REASON_INVALID_REQUEST, 6);
ASSERT_EQ(RP1_GPCLK_REASON_RESOURCE_UNAVAILABLE, 7);
ASSERT_EQ(RP1_GPCLK_REASON_STARTUP_CONFLICT, 8);
ASSERT_EQ(RP1_GPCLK_REASON_DMA_FAILED, 9);
ASSERT_EQ(RP1_GPCLK_REASON_CLOCK_FAILED, 10);
ASSERT_EQ(RP1_GPCLK_REASON_PINCTRL_FAILED, 11);
ASSERT_EQ(RP1_GPCLK_REASON_READBACK_FAILED, 12);
ASSERT_EQ(RP1_GPCLK_REASON_CLEANUP_FAILED, 13);
ASSERT_EQ(RP1_GPCLK_REASON_COMPATIBILITY_REJECTED, 14);
ASSERT_EQ(RP1_GPCLK_REASON_INTERNAL_ERROR, 15);
ASSERT_EQ(RP1_GPCLK_CAP_SUBMIT_EVENTS, 1ULL << 0);
ASSERT_EQ(RP1_GPCLK_CAP_STOP_DRAIN, 1ULL << 1);
ASSERT_EQ(RP1_GPCLK_CAP_STABLE_STATE, 1ULL << 2);
ASSERT_EQ(RP1_GPCLK_CAP_ROUTE_IDENTITY, 1ULL << 3);
ASSERT_EQ(RP1_GPCLK_CAP_COMPAT_IDENTITY, 1ULL << 4);
ASSERT_EQ(RP1_GPCLK_CAP_CLEANUP_FAULT_LATCH, 1ULL << 5);
ASSERT_EQ(RP1_GPCLK_CAP_OUTPUT_INHIBIT, 1ULL << 6);
ASSERT_EQ(RP1_GPCLK_CAP_PASSIVE_SNAPSHOT, 1ULL << 7);
ASSERT_EQ(RP1_GPCLK_CAP_BOUNDED_DMA_CHUNKS, 1ULL << 8);
ASSERT_EQ(RP1_GPCLK_OBSERVATION_UNKNOWN, 0);
ASSERT_EQ(RP1_GPCLK_OBSERVATION_FALSE, 1);
ASSERT_EQ(RP1_GPCLK_OBSERVATION_TRUE, 2);
ASSERT_EQ(RP1_GPCLK_DRAIN_NONE, 0);
ASSERT_EQ(RP1_GPCLK_DRAIN_ACTIVE, 1);
ASSERT_EQ(RP1_GPCLK_DRAIN_COMPLETE, 2);
ASSERT_EQ(RP1_GPCLK_MAX_TONES, 64);
ASSERT_EQ(RP1_GPCLK_MAX_EVENTS, 512);
ASSERT_EQ(RP1_GPCLK_DITHER_PERIOD_MAX, 4294967295U);
ASSERT_EQ(RP1_GPCLK_FRACTIONAL_BITS, 16);
ASSERT_EQ(RP1_GPCLK_TICK_DIVIDER, 511);
ASSERT_EQ(RP1_GPCLK_EVENT_DURATION_NS_MIN, 10220ULL);
ASSERT_EQ(RP1_GPCLK_EVENT_DURATION_NS_MAX, 9223372036854775807ULL);
ASSERT_EQ(RP1_GPCLK_REQUEST_DURATION_NS_MAX, 9223372036854775807ULL);
ASSERT_EQ(RP1_GPCLK_DMA_CHUNK_DURATION_NS, 1000000000ULL);
ASSERT_EQ(RP1_GPCLK_DRIVE_MA_2, 2);
ASSERT_EQ(RP1_GPCLK_DRIVE_MA_4, 4);
ASSERT_EQ(RP1_GPCLK_DRIVE_MA_8, 8);
ASSERT_EQ(RP1_GPCLK_DRIVE_MA_12, 12);
ASSERT_EQ(RP1_GPCLK_DRIVE_SUPPORT_ALLOWED_MASK, 0x0f);

int main(void)
{
    puts("uapi contract: PASS");
    return 0;
}
