/* SPDX-License-Identifier: GPL-2.0-only OR MIT */
#ifndef RP1_GPCLK_TARGET_FAULT_H
#define RP1_GPCLK_TARGET_FAULT_H

#include <linux/types.h>

enum rp1_gpclk_target_fault_stage {
	RP1_GPCLK_TARGET_FAULT_CLOCK_SETUP = 1,
	RP1_GPCLK_TARGET_FAULT_PREPARE = 2,
	RP1_GPCLK_TARGET_FAULT_PIN_ACTIVE = 3,
	RP1_GPCLK_TARGET_FAULT_CLOCK_ENABLE = 4,
	RP1_GPCLK_TARGET_FAULT_DMA_PREPARE = 5,
	RP1_GPCLK_TARGET_FAULT_DMA_SUBMIT = 6,
	RP1_GPCLK_TARGET_FAULT_DMA_COMPLETION = 7,
	RP1_GPCLK_TARGET_FAULT_READBACK = 8,
	RP1_GPCLK_TARGET_FAULT_CLEANUP_STOP_TICK = 9,
	RP1_GPCLK_TARGET_FAULT_CLEANUP_TERMINATE_DMA = 10,
	RP1_GPCLK_TARGET_FAULT_CLEANUP_DISABLE = 11,
	RP1_GPCLK_TARGET_FAULT_CLEANUP_UNPREPARE = 12,
	RP1_GPCLK_TARGET_FAULT_CLEANUP_PIN_SAFE = 13,
	RP1_GPCLK_TARGET_FAULT_CLEANUP_RESTORE_PARENT = 14,
	RP1_GPCLK_TARGET_FAULT_CLEANUP_RESTORE_RATE = 15,
};

#ifdef RP1_GPCLK_TARGET_FAULT_STAGE
#if RP1_GPCLK_TARGET_FAULT_STAGE < 1 || RP1_GPCLK_TARGET_FAULT_STAGE > 15
#error "RP1_GPCLK_TARGET_FAULT_STAGE is outside the reviewed test range"
#endif
static inline bool rp1_gpclk_target_fault(unsigned int stage)
{
	return RP1_GPCLK_TARGET_FAULT_STAGE == stage;
}
#else
static inline bool rp1_gpclk_target_fault(unsigned int stage)
{
	(void)stage;
	return false;
}
#endif

#endif /* RP1_GPCLK_TARGET_FAULT_H */
