# SPDX-License-Identifier: MIT
# Installed only by the explicitly authorized runtime deployment tool.
[Service]
ExecStart=
ExecStart=/usr/bin/python3 /usr/lib/rp1-gpclk-dkms/runtime_manager.py
UnsetEnvironment=RP1_GPCLK_SOURCE_DEVELOPMENT_BINDING
ReadWritePaths=
ReadWritePaths=/var/lib/rp1-gpclk-dkms /etc/systemd/system
